name: firebase_notification_example
description: A Flutter example app demonstrating the Firebase Notification Handler package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_notifyhub:
    path: ../
  cupertino_icons: ^1.0.6
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
